# Generated by Django 5.0.6 on 2024-07-04 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_food_cosumed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cosumed",
            new_name="Consumed",
        ),
    ]
